<a href="https://colab.research.google.com/github/nganduong31231023222-ai/UEH_KTLT_eco25/blob/buoi3/04_Ph%C3%A2n_t%C3%ADch_%C4%91%E1%BB%8Bnh_l%C6%B0%E1%BB%A3ng_d%C3%B9ng_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
v = list(range(1, 6))
v

[1, 2, 3, 4, 5]

In [ ]:
2 * v

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [ ]:
import numpy as np
v = np.arange(1, 6)
v

array([1, 2, 3, 4, 5])

In [ ]:
2 * v

array([ 2,  4,  6,  8, 10])

In [ ]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a * b
c

array([ 4, 10, 18])

In [ ]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
print(a.shape)

(3, 5)

In [ ]:
a.ndim

2

In [ ]:
a.dtype.name

'int64'

In [ ]:
import numpy as np
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [ ]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
import numpy as np
a = np.array([[0, 1, 2, 3],
[10, 11, 12, 13],
[20, 21, 22, 23]])
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

In [ ]:
a = np.array([[0, 1, 2, 3], [10, 11, 12, 13], [20, 21, 22, 23]])
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

In [ ]:
import numpy as np
import pandas as pd

df = pd.DataFrame(
    {
        "a": [4, 5, 6],
        "b": [7, 8, 9],
        "c": [10, 11, 12],
    },
    index=[1, 2, 3]
)
df

   a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print('pandas imported')

pandas imported

In [ ]:
s = pd.Series([1,3,5,np.nan,6,8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [ ]:
dates = pd.date_range('20181001', periods=6)
dates

DatetimeIndex(['2018-10-01', '2018-10-02', '2018-10-03', '2018-10-04',
               '2018-10-05', '2018-10-06'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))
df

                   A         B         C         D
2018-10-01  0.716541  1.071183 -1.511278  0.474789
2018-10-02  1.073750  1.864450  1.163124 -0.262877
2018-10-03 -0.083318 -1.819593  1.004364  0.974667
2018-10-04 -0.202116 -0.196481  0.021917  0.068552
2018-10-05  0.221108  0.904763 -1.074104  1.693669
2018-10-06 -1.799098 -0.422002  0.575705 -0.267147

In [ ]:
df = pd.DataFrame(np.random.randn(3,5), index=['student1','student2','student3'], columns=list('ABCDE'))
df

                 A         B         C         D         E
student1 -0.124528 -0.786210  0.297035 -3.382619  0.990119
student2  2.463190  1.036981 -1.293855  0.196585 -0.426962
student3  0.338696  0.461729 -0.192480 -0.088219  2.953483

In [ ]:
df2 = pd.DataFrame({ 'A' : 1.,
'B' : pd.Timestamp('20181001'),
'C' : pd.Series(2.5,index=list(range(4)),dtype='float32'),
'D' : np.array([3] * 4,dtype='int32'),
'E' : pd.Categorical(["test","train","test","train"]),
'F' : 'foo' })
df2

     A          B    C  D      E    F
0  1.0 2018-10-01  2.5  3   test  foo
1  1.0 2018-10-01  2.5  3  train  foo
2  1.0 2018-10-01  2.5  3   test  foo
3  1.0 2018-10-01  2.5  3  train  foo

In [ ]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object